clear all; close all; clc;

A11=0.5; A12=.5; F11=5; F12=3; Ph11=0.5; Ph12=0;Tm=0.001;

sim('sk_R3GDL_2017');

%q vs q ref
figure();subplot(3,1,1);plot(t,q(:,1),t,qr(:,1));grid;xlabel('Tiempo(s)');ylabel('q1 vs q1 robot(rad)');legend('q1','q1rob','location','southwest');...
    subplot(3,1,2);plot(t,q(:,2),t,qr(:,2));grid;xlabel('Tiempo(s)');ylabel('q2 vs q2 robot(m)');legend('q2','q2rob','location','northwest');...
    subplot(3,1,3);plot(t,q(:,3),t,qr(:,3));grid;xlabel('Tiempo(s)');ylabel('q3 vs q3 robot(m)');legend('q3','q3rob','location','southwest');

%qd vs qd ref
figure();subplot(3,1,1);plot(t,qd(:,1),t,qdr(:,1));grid;xlabel('Tiempo(s)');ylabel('qd1 vs qd1 robot(rad/s)');legend('qd1','qd1rob','location','southwest');...
    subplot(3,1,2);plot(t,qd(:,2),t,qdr(:,2));grid;xlabel('Tiempo(s)');ylabel('qd2 vs qd2 robot(rad/s)');legend('qd2','qd2rob','location','northwest');...
    subplot(3,1,3);plot(t,qd(:,3),t,qdr(:,3));grid;xlabel('Tiempo(s)');ylabel('qd3 vs qd3 robot(rad/s)');legend('qd3','qd3rob','location','northwest');

%qdd vs qdd ref
figure();subplot(3,1,1);plot(t,qdd(:,1),t,qddr(:,1));grid;xlabel('Tiempo(s)');ylabel('qdd1 vs qdd1 robot(rad/s^2)');legend('qdd1','qdd1rob','location','southwest');...
    subplot(3,1,2);plot(t,qdd(:,2),t,qddr(:,2));grid;xlabel('Tiempo(s)');ylabel('qdd2 vs qdd2 robot(rad/s^2)');legend('qdd2','qdd2rob','location','northwest');...
    subplot(3,1,3);plot(t,qdd(:,3),t,qddr(:,3));grid;xlabel('Tiempo(s)');ylabel('qdd3 vs qdd3 robot(rad/s^2)');legend('qdd3','qdd3rob','location','northwest');

%Fuerzas y pares
% figure();subplot(3,1,1);plot(t,Im(:,1));grid;xlabel('Tiempo(s)');ylabel('N1(N*m)');...
%     subplot(3,1,2);plot(t,Im(:,2));grid;xlabel('Tiempo(s)');ylabel('F2(N)');...
%     subplot(3,1,3);plot(t,Im(:,3));grid;xlabel('Tiempo(s)');ylabel('F3(N)');
